### ISSUE TITLE
Improve support for PRO edition

### ISSUE THREAD

**Issue by whybtech** [sugarcrmlabs/SystemData#7]
I'm trying to export from SystemData with a PRO edition (tested with version 8.0.0) and my local configuration show some PHP warnings or API failures on results : 
* Unknown constant `ACL_ALLOW_SELECTED_TEAMS` when I'm selecting Roles
* Unknown table `pmse_project` when I'm selecting Awf

I'm going to make a pull request about this, feel free to comment :wink:

**Comment by esimonetti** [comment]
Hi Oberge,

Please see if this fixes your issues: https://github.com/sugarcrmlabs/SystemData/pull/11

Thanks!

**Comment by whybtech** [comment]
Hi esimonetti

Thanks a lot for that support
